import type { Metadata } from "next";
import { Inter,Crete_Round,Work_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";


const creteRound = Crete_Round({
  weight : ["400"],
  subsets: ["latin"],
  variable :"--font-creteRound"
})
const workSans = Work_Sans({
  weight:["500", "600"],
  subsets:["latin"],
  variable :"--font-workSans"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${creteRound.variable}  ${workSans.variable} overflow-x-hidden`}>
        <div>
          <Navbar/>
        </div>
        {children}
        </body>
    </html>
  );
}
